temp_list = [{'name_post': 'Request for Proposals - ARB Distribution',
              'link': 'https://gov.uniswap.org/t/request-for-proposals-arb-distribution/21287',
              'views_post': '1,5 тыс.', 'date_post': '15 ч'},
             {'name_post': 'Deploy Uniswap v3 on Filecoin Virtual Machine (FVM)',
              'link': 'https://gov.uniswap.org/t/deploy-uniswap-v3-on-filecoin-virtual-machine-fvm/21309',
              'views_post': '772', 'date_post': '2 дн'},
             {'name_post': '[RFC] - BrincX - Real Yield, Analytics, Liquid Derivatives for UniV3',
              'link': 'https://gov.uniswap.org/t/rfc-brincx-real-yield-analytics-liquid-derivatives-for-univ3/21390',
              'views_post': '614', 'date_post': '2 дн'},
             {'name_post': '[RFC] Should Uniswap Enable a Dedicated Governance Tool for Delegates and Voters?',
              'link': 'https://gov.uniswap.org/t/rfc-should-uniswap-enable-a-dedicated-governance-tool-for-delegates-and-voters/21044',
              'views_post': '884', 'date_post': '3 дн'}, {'name_post': 'UF Bridge Recommendations',
                                                          'link': 'https://gov.uniswap.org/t/uf-bridge-recommendations/21513',
                                                          'views_post': '205', 'date_post': '3 дн'},
             {'name_post': '[RFC] - Gauntlet - Dynamic Incentive Optimization for Uniswap V3 on Arbitrum',
              'link': 'https://gov.uniswap.org/t/rfc-gauntlet-dynamic-incentive-optimization-for-uniswap-v3-on-arbitrum/21426',
              'views_post': '341', 'date_post': '3 дн'},
             {'name_post': 'UF Bridge Assessment Committee Results - Framework and Evaluations',
              'link': 'https://gov.uniswap.org/t/uf-bridge-assessment-committee-results-framework-and-evaluations/21512',
              'views_post': '301', 'date_post': '3 дн'},
             {'name_post': '[RFC] - Flashstake - Enabling upfront yield for Uniswap Liquidity V2&V3',
              'link': 'https://gov.uniswap.org/t/rfc-flashstake-enabling-upfront-yield-for-uniswap-liquidity-v2-v3/21410',
              'views_post': '677', 'date_post': '3 дн'},
             {'name_post': '[RFC] - Alastor | w3s - Create a UNI-ARB Working Group',
              'link': 'https://gov.uniswap.org/t/rfc-alastor-w3s-create-a-uni-arb-working-group/21376',
              'views_post': '472', 'date_post': '3 дн'},
             {'name_post': '[RFC] - LI.FI - MMA infrastructure development for Uniswap',
              'link': 'https://gov.uniswap.org/t/rfc-li-fi-mma-infrastructure-development-for-uniswap/21444',
              'views_post': '373', 'date_post': '3 дн'}, {'name_post': 'Deploy Uniswap v3 on Ontology EVM',
                                                          'link': 'https://gov.uniswap.org/t/deploy-uniswap-v3-on-ontology-evm/21224',
                                                          'views_post': '636', 'date_post': '4 дн'}, {
                 'name_post': '[RFC] - OpenBlock Labs - Developing a systems analytics dashboard to optimize incentive distribution on new venues',
                 'link': 'https://gov.uniswap.org/t/rfc-openblock-labs-developing-a-systems-analytics-dashboard-to-optimize-incentive-distribution-on-new-venues/21378',
                 'views_post': '297', 'date_post': '5 дн'},
             {'name_post': '[RFC] - Gamma Strategies - Distribute at least 1/3 of $ARB airdrop as liquidity incentives',
              'link': 'https://gov.uniswap.org/t/rfc-gamma-strategies-distribute-at-least-1-3-of-arb-airdrop-as-liquidity-incentives/21345',
              'views_post': '932', 'date_post': '5 дн'}, {'name_post': 'StableLab Delegate Platform',
                                                          'link': 'https://gov.uniswap.org/t/stablelab-delegate-platform/21240',
                                                          'views_post': '411', 'date_post': '5 дн'}]
